"""Task-specific workspace with controls next to the content they affect."""
from i18n import tr
from PySide6.QtCore import Qt, QSize, QSettings
from PySide6.QtWidgets import (QAbstractItemView, QDoubleSpinBox, QGroupBox, QButtonGroup, QCheckBox, QComboBox, QFormLayout, QHBoxLayout, QLabel,
    QLineEdit, QListWidget, QPlainTextEdit, QScrollArea, QProgressBar, QSlider, QSpinBox, QScrollBar, QPushButton, QSplitter, QStackedWidget, QVBoxLayout, QWidget)
from profile_panel import ProfilePanel
from timeline import RangeTimeline


def build_window(w):
    root = QWidget()
    layout = QVBoxLayout(root)
    root.setStyleSheet("""
        QPushButton { padding: 7px 10px; }
        QPushButton[primary="true"] { background: #176c92; color: white; font-weight: 600; }
        QPushButton[primary="true"]:disabled { background: #777; color: #ddd; }
        QPushButton:checked { border: 2px solid #176c92; font-weight: 600; }
        QLineEdit, QComboBox { padding: 4px; }
        QListWidget::item { padding: 7px; }
    """)
    toolbar = QHBoxLayout()
    title = QLabel("ArcadeClip")
    title.setStyleSheet("font-size:18px;font-weight:600")
    toolbar.addWidget(title)
    toolbar.addWidget(QLabel(tr('현재 영상')))
    w.source_picker = QComboBox()
    w.source_picker.setMinimumWidth(180)
    w.source_picker.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToMinimumContentsLengthWithIcon)
    w.source_picker.setAccessibleName(tr('현재 영상 전환 · 클립은 영상별로 관리'))
    w.source_picker.currentIndexChanged.connect(lambda index: w.files.setCurrentRow(index))
    toolbar.addWidget(w.source_picker, 1)
    w.busy_controls.append(w.source_picker)
    w.button(tr('작업 열기'), w.open_session, toolbar)
    w.button(tr('작업 저장'), w.save_session, toolbar)
    w.button(tr('도움말'), w.show_controls, toolbar, busy=False)
    w.button(tr('Settings'), w.show_advanced, toolbar, busy=False)
    layout.addLayout(toolbar)
    catalog = w.catalog = QGroupBox(tr('곡 데이터'), w)
    catalog.setStyleSheet("QGroupBox { border:1px solid #627988; border-radius:8px; margin-top:8px; padding:4px; }"
                         "QGroupBox::title { subcontrol-origin:margin; left:12px; padding:0 5px; }")
    catalog_row = QHBoxLayout(catalog)
    w.catalog_values = []
    for title in (tr('등록된 곡'), tr('보유 자켓'), tr('곡·자켓 용량')):
        column = QHBoxLayout()
        caption = QLabel(title)
        value = QLabel(tr('확인 중…'))
        value.setStyleSheet("font-size:16px; font-weight:600; padding:2px 0;")
        column.addWidget(caption)
        column.addWidget(value)
        catalog_row.addLayout(column, 1)
        w.catalog_values.append(value)
    w.button(tr('곡 데이터 업데이트'), w.update_jackets, catalog_row)
    catalog.hide()
    stages = QHBoxLayout()
    w.stage_group = QButtonGroup(w)
    for index, name in enumerate((tr('영상 선택'), tr('시간 선택'), tr('인식 영역'), tr('클립 확인'), tr('파일 저장'))):
        button = QPushButton(f"{index + 1}  {name}")
        button.setCheckable(True)
        w.stage_group.addButton(button, index)
        stages.addWidget(button)
    w.stage_group.idClicked.connect(w.set_stage)
    w.youtube_tab = QPushButton(tr('YouTube 다운로드'))
    w.youtube_tab.setCheckable(True)
    w.stage_group.addButton(w.youtube_tab, 5)
    stages.addWidget(w.youtube_tab)
    w.youtube_tab.hide()
    layout.addLayout(stages)
    w.source_context = QLabel()
    w.source_context.setTextFormat(Qt.TextFormat.PlainText)
    w.source_context.setWordWrap(True)
    w.source_context.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
    w.source_context.hide()
    w.stage_hint = QLabel()
    w.stage_hint.setWordWrap(True)
    layout.addWidget(w.stage_hint)
    splitter = QSplitter()
    w.workspace_splitter = splitter
    w.list_stack = QStackedWidget()
    source_panel = QWidget()
    source_layout = QVBoxLayout(source_panel)
    source_layout.addWidget(QLabel(tr('파일이나 폴더를 추가하거나 영상을 여기에 놓으세요.')))
    w.files = QListWidget()
    w.files.setAccessibleName(tr('영상 목록'))
    w.files.currentItemChanged.connect(w.select_file)
    source_layout.addWidget(w.files)
    w.source_actions = QWidget()
    row = QHBoxLayout(w.source_actions)
    row.setContentsMargins(0, 0, 0, 0)
    w.button(tr('파일 추가'), w.add_files, row).setProperty("primary", True)
    w.button(tr('폴더 추가'), w.add_folder, row)
    source_layout.insertWidget(1, w.source_actions)
    w.list_stack.addWidget(source_panel)
    clip_panel = QWidget()
    clip_layout = QVBoxLayout(clip_panel)
    clip_layout.addWidget(QLabel(tr('클립 목록')))
    w.player_filter = QLineEdit()
    w.player_filter.setPlaceholderText(tr('플레이어 이름 검색'))
    w.player_filter.textChanged.connect(w.filter_ranges)
    clip_layout.addWidget(w.player_filter)
    w.show_unknown = QCheckBox(tr('이름 미확인도 표시'))
    w.show_unknown.setChecked(True)
    w.show_unknown.toggled.connect(w.filter_ranges)
    clip_layout.addWidget(w.show_unknown)
    w.show_unknown_songs = QCheckBox(tr('곡 미확인 구간 표시'))
    w.show_unknown_songs.setToolTip(tr('기본값은 숨김입니다. 보이는 클립 저장에는 표시된 구간만 포함됩니다.'))
    w.show_unknown_songs.toggled.connect(w.filter_ranges)
    clip_layout.addWidget(w.show_unknown_songs)
    row = QHBoxLayout()
    w.check_visible_button = w.button(tr('보이는 클립 체크'), lambda: w.check_clips(True), row, busy=False)
    w.uncheck_visible_button = w.button(tr('체크 해제'), lambda: w.check_clips(False), row, busy=False)
    clip_layout.addLayout(row)
    w.range_list = QListWidget()
    w.range_list.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)
    w.range_list.setToolTip(tr('Shift: 연속 선택 · Ctrl: 개별 선택 · 체크박스: 저장 대상'))
    w.range_list.setAccessibleName(tr('클립 목록 · 체크하여 저장 선택'))
    w.range_list.setWordWrap(True)
    w.range_list.setVerticalScrollMode(QAbstractItemView.ScrollMode.ScrollPerPixel)
    w.range_list.setAutoScroll(False)
    w.range_list.setIconSize(QSize(44, 44))
    w.range_list.currentRowChanged.connect(w.activate_clip)
    w.range_list.itemChanged.connect(w.clip_checked)
    clip_layout.addWidget(w.range_list, 1)
    w.empty_clips = QLabel()
    w.empty_clips.setWordWrap(True)
    clip_layout.addWidget(w.empty_clips)
    clip_actions = QHBoxLayout()
    w.remove_clip_button = w.button(tr('목록에서 제거'), w.remove_range, clip_actions)
    w.button(tr('클립 직접 추가'), w.add_range, clip_actions)
    clip_layout.addLayout(clip_actions)
    w.button(tr('선택한 클립 합치기'), lambda: w.merge_clips(), clip_layout)
    w.range_list.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
    w.range_list.customContextMenuRequested.connect(lambda pos: w.clip_context_menu(
        w.range_list.row(w.range_list.itemAt(pos)), w.range_list.viewport().mapToGlobal(pos)))
    w.remove_clip_button.setToolTip(tr('원본 영상은 유지됩니다. 현재 클립의 되돌리기로 복구할 수 있습니다.'))
    w.export_footer = QWidget()
    footer = QVBoxLayout(w.export_footer)
    footer.setContentsMargins(0, 0, 0, 0)
    w.selection_summary = QLabel()
    w.selection_summary.setWordWrap(True)
    footer.addWidget(w.selection_summary)
    w.save_all_button = w.button(tr('전체 저장 (0)'), lambda: w.export_ranges(True), footer)
    w.save_all_button.setProperty("primary", True)
    w.save_checked_button = w.button(tr('선택 저장 (0)'), lambda: w.export_ranges(False), footer)
    w.save_all_button.setToolTip(tr('현재 필터로 보이는 클립의 저장 설정을 엽니다.'))
    w.save_checked_button.setToolTip(tr('체크한 클립의 저장 대상과 파일명을 확인합니다.'))
    w.save_checked_button.setProperty("primary", True)
    clip_layout.addWidget(w.export_footer)
    w.list_stack.addWidget(clip_panel)
    splitter.addWidget(w.list_stack)
    center = QWidget()
    w.preview_panel = center
    center_layout = QVBoxLayout(center)
    center_layout.setContentsMargins(0, 0, 0, 0)
    w.current_clip_label = QLabel(tr('미리보기'))
    w.current_clip_label.setTextFormat(Qt.TextFormat.PlainText)
    w.current_clip_label.setWordWrap(True)
    center_layout.addWidget(w.current_clip_label)
    center_layout.addWidget(w.preview, 1)
    w.timeline_panel = QWidget()
    timeline_layout = QVBoxLayout(w.timeline_panel)
    timeline_layout.setContentsMargins(0, 0, 0, 0)
    center_layout.addWidget(w.timeline_panel)
    w.full_timeline_label = QLabel()
    timeline_layout.addWidget(w.full_timeline_label)
    w.full_timeline = RangeTimeline()
    timeline_layout.addWidget(w.full_timeline)
    w.full_scroll = QScrollBar(Qt.Orientation.Horizontal)
    w.full_scroll.setAccessibleName(tr('전체 시간축 가로 이동'))
    w.full_scroll.valueChanged.connect(w.scroll_full)
    w.full_timeline.viewChanged.connect(
        lambda low, high: w.sync_timeline_scroll(w.full_scroll, w.full_timeline.extent, low, high))
    timeline_layout.addWidget(w.full_scroll)
    w.zoom_panel = QWidget()
    zoom_layout = QVBoxLayout(w.zoom_panel)
    zoom_layout.setContentsMargins(0, 0, 0, 0)
    timeline_layout.addWidget(w.zoom_panel)
    timeline_tools = QHBoxLayout()
    timeline_tools.addWidget(QLabel(tr('선택 주변 확대')), 1)
    w.button("-", lambda: w.zoom_timeline.zoom(.8), timeline_tools, busy=False)
    w.button("+", lambda: w.zoom_timeline.zoom(1.25), timeline_tools, busy=False)
    w.button(tr('전체 시간 보기'), lambda: w.zoom_timeline.fit(), timeline_tools, busy=False)
    zoom_layout.addLayout(timeline_tools)
    zoom_layout.addWidget(QLabel(tr('위: 자동 인식 클립    아래: 직접 추가한 클립')))
    w.zoom_timeline = RangeTimeline()
    zoom_layout.addWidget(w.zoom_timeline)
    w.zoom_scroll = QScrollBar(Qt.Orientation.Horizontal)
    w.zoom_scroll.setAccessibleName(tr('확대 시간축 가로 이동'))
    w.zoom_scroll.valueChanged.connect(w.scroll_zoom)
    zoom_layout.addWidget(w.zoom_scroll)
    w.zoom_timeline.viewChanged.connect(w.sync_zoom_view)
    for timeline in (w.full_timeline, w.zoom_timeline):
        timeline.changed.connect(w.timeline_changed)
        timeline.seek.connect(w.scrub)
        timeline.committed.connect(w.commit_timeline)
        timeline.activate.connect(w.select_timeline_clip)
        timeline.contextRequested.connect(w.clip_context_menu)
    splitter.addWidget(center)
    w.detail_stack = QStackedWidget()
    w.detail_stack.setMinimumWidth(260)
    def page(title):
        panel = QWidget()
        body = QVBoxLayout(panel)
        heading = QLabel(title)
        heading.setStyleSheet("font-size:16px;font-weight:600")
        body.addWidget(heading)
        w.detail_stack.addWidget(panel)
        return body
    body = page(tr('YouTube 영상 가져오기'))
    body.addWidget(QLabel(tr('YouTube 링크')))
    w.url = QLineEdit()
    w.url.setPlaceholderText("https://www.youtube.com/…")
    body.addWidget(w.url)
    w.url_error = QLabel()
    w.url_error.setWordWrap(True)
    w.url_error.setStyleSheet('color: #ffb4ab;')
    w.url_error.hide()
    body.addWidget(w.url_error)
    w.url.textChanged.connect(w.url_error.hide)
    w.button(tr('영상 정보 확인 →'), w.inspect_link, body).setProperty("primary", True)
    body.addStretch()
    w.source_next = w.button(tr('시간 선택으로 →'), lambda: w.set_stage(1), body)
    w.source_next.setProperty("primary", True)
    body = page(tr('시간 선택'))
    w.time_controls = body.parentWidget()
    body.itemAt(0).widget().hide()
    form = QHBoxLayout()
    w.start_time, w.end_time = QLineEdit("00:00:00.000"), QLineEdit("00:00:00.000")
    for label, field in ((tr('시작'), w.start_time), (tr('끝'), w.end_time)):
        form.addWidget(QLabel(label))
        form.addWidget(field)
    w.start_time.textChanged.connect(w.update_timelines)
    w.end_time.textChanged.connect(w.update_timelines)
    body.addLayout(form)
    row = QHBoxLayout()
    w.local_time_controls = [w.button(tr('현재 위치를 시작으로'), lambda: w.mark(w.start_time), row, busy=False),
                             w.button(tr('현재 위치를 끝으로'), lambda: w.mark(w.end_time), row, busy=False)]
    body.addLayout(row)
    w.button(tr('전체 구간'), w.select_whole, row)
    w.local_time_controls.append(w.button(tr('선택 구간 재생'), w.play_range, row, busy=False))
    body.addStretch()
    w.local_time_controls.append(w.button(tr('인식 영역으로 →'), lambda: w.set_stage(2), row))
    w.local_time_controls[-1].setProperty("primary", True)
    body = page(tr('자켓과 글자 위치'))
    w.profile = ProfilePanel(w.preview)
    w.profile.directory = w.directory
    w.profile.error.connect(w.fail)
    w.profile.message.connect(lambda text: w.status.setText(text))
    profile_scroll = QScrollArea()
    profile_scroll.setWidgetResizable(True)
    profile_scroll.setFrameShape(QScrollArea.Shape.NoFrame)
    profile_scroll.setWidget(w.profile)
    body.addWidget(profile_scroll, 1)
    w.analysis_range_summary = QLabel()
    w.analysis_range_summary.setWordWrap(True)
    body.addWidget(w.analysis_range_summary)
    w.button(tr('현재 화면 인식 확인'), w.recognize_frame, body)
    w.button(tr('이 구간에서 곡 찾기 →'), w.analyze_range, body).setProperty("primary", True)
    body = page(tr('현재 클립'))
    offsets = QGroupBox(tr('클립 시작·끝 일괄 조정'))
    offset_layout = QFormLayout(offsets)
    w.clip_start_offset, w.clip_end_offset = QDoubleSpinBox(), QDoubleSpinBox()
    for title, control in ((tr('시작 오프셋'), w.clip_start_offset), (tr('끝 오프셋'), w.clip_end_offset)):
        control.setRange(-600, 600)
        control.setDecimals(2)
        control.setSingleStep(.5)
        control.setSuffix(tr(' 초'))
        offset_layout.addRow(title, control)
    offset_hint = QLabel(tr('현재 영상의 자동 인식 결과 기준\n−: 앞당김 / +: 늦춤'))
    offset_hint.setWordWrap(True)
    offset_layout.addRow(offset_hint)
    apply_offsets = QPushButton(tr('모든 클립에 일괄 적용'))
    apply_offsets.clicked.connect(w.apply_clip_offsets)
    w.busy_controls.append(apply_offsets)
    offset_layout.addRow(apply_offsets)
    w.clip_start_offset.setValue(-10)
    w.clip_end_offset.setValue(10)
    reset_detected = QPushButton(tr('자동 인식 결과로 복원'))
    reset_detected.setToolTip(tr('현재 영상의 삭제·편집한 자동 클립을 원본으로 복원합니다. 직접 추가한 클립은 유지합니다.'))
    reset_detected.clicked.connect(w.reset_detected_clips)
    w.busy_controls.append(reset_detected)
    offset_layout.addRow(reset_detected)
    w.follow_clip = QCheckBox(tr('클립 선택·재생 위치를 따라 확대 시간축 이동'), w)
    w.follow_clip.setChecked(QSettings("ArcadeClip", "ArcadeClip").value("follow_clip", True, type=bool))
    w.follow_clip.toggled.connect(lambda checked: QSettings("ArcadeClip", "ArcadeClip").setValue("follow_clip", checked))
    w.follow_clip.hide()
    body.insertWidget(0, offsets)
    form = QFormLayout()
    w.clip_fields = {}
    for key, title in (("title", tr('곡명')), ("player", tr('1P 이름')), ("player2", tr('2P 이름')),
                       ("achievement", tr('1P 달성률')), ("achievement2", tr('2P 달성률')), ("start", tr('시작')), ("end", tr('끝'))):
        field = QLineEdit()
        field.setMaxLength(300)
        w.clip_fields[key] = field
        form.addRow(title, field)
    body.addLayout(form)
    w.clip_reviewed = QCheckBox(tr('검수 완료로 표시'))
    body.addWidget(w.clip_reviewed)
    row = QHBoxLayout()
    w.button(tr('수정 적용'), w.apply_clip_details, row)
    w.button(tr('되돌리기'), w.undo_clip_edit, row)
    body.addLayout(row)
    row = QHBoxLayout()
    w.button(tr('시작 부분 재생'), lambda: w.check_edge(False), row, busy=False)
    w.button(tr('끝 부분 재생'), lambda: w.check_edge(True), row, busy=False)
    body.addLayout(row)
    w.loop_clip = QCheckBox(tr('이 구간 반복'))
    body.addWidget(w.loop_clip)
    body.addStretch()
    review_fields = QWidget()
    review_fields_layout = QVBoxLayout(review_fields)
    review_fields_layout.setContentsMargins(0, 0, 0, 0)
    # The field editor scrolls; frequent playback/apply actions stay in view.
    for _ in range(4):
        item = body.takeAt(0)
        if item.widget():
            review_fields_layout.addWidget(item.widget())
        else:
            item.layout().setParent(None)
            review_fields_layout.addLayout(item.layout())
    review_scroll = QScrollArea()
    review_scroll.setWidgetResizable(True)
    review_scroll.setFrameShape(QScrollArea.Shape.NoFrame)
    review_scroll.setWidget(review_fields)
    body.insertWidget(0, review_scroll, 1)
    body = page(tr('저장 대상 확인'))
    w.button(tr('클립 선택으로 돌아가기'), lambda: w.set_stage(3), body)
    w.export_mode = QComboBox(w)
    w.export_mode.addItem(tr('정확한 저장'), "accurate")
    w.export_mode.addItem(tr('빠른 저장 · 경계 차이 가능'), "fast")
    w.export_mode.setCurrentIndex(1)
    w.export_mode.hide()
    w.export_audio = True
    w.export_options = {}
    w.export_settings_summary = QLabel(tr('원본 빠른 복사 · 소리 포함'))
    w.export_settings_summary.setWordWrap(True)
    w.decoder_threads = QSpinBox(w)
    w.decoder_threads.setRange(0, 64)
    w.decoder_threads.setSpecialValueText(tr('자동 · 최대 32스레드'))
    w.decoder_threads.hide()
    w.analysis_workers = QSpinBox(w)
    w.analysis_workers.setRange(0, 61)
    w.analysis_workers.setSpecialValueText(tr('자동 · CPU와 분석량에 맞춤'))
    w.analysis_workers.hide()
    w.ocr_workers = QSpinBox(w)
    w.ocr_workers.setRange(0, 32)
    w.ocr_workers.setSpecialValueText(tr('자동 · CPU 수에 맞춤'))
    w.ocr_workers.hide()
    w.gpu_decode = QCheckBox(tr('실험용 GPU 영상 디코딩 (D3D11VA)'), w)
    w.gpu_decode.setToolTip(tr('곡 탐색 영상 디코딩만 GPU 사용. 지원하지 않으면 CPU로 복귀합니다. OCR은 CPU 병렬 처리합니다.'))
    w.gpu_decode.hide()
    w.encoder_crf = QSpinBox(w)
    w.encoder_crf.setRange(0, 51)
    w.encoder_crf.setValue(18)
    w.encoder_crf.hide()
    w.encoder_preset = QComboBox(w)
    w.encoder_preset.addItems(["ultrafast", "fast", "medium", "slow"])
    w.encoder_preset.setCurrentText("fast")
    w.encoder_preset.hide()
    w.export_summary = QLabel(tr('저장할 클립을 선택하세요.'))
    w.export_summary.setWordWrap(True)
    body.addWidget(w.export_summary)
    body.addWidget(QLabel(tr('저장 폴더')))
    w.output_directory = QLineEdit(str(w.directory / "clips"))
    body.addWidget(w.output_directory)
    w.export_date_folder = QCheckBox(tr('날짜와 시간으로 새 폴더 만들기'))
    w.export_date_folder.setChecked(True)
    w.export_date_folder.setToolTip(tr('저장 시작 시 대상 폴더 아래에 YYYY-MM-DD_HH-MM-SS 형식의 폴더를 만듭니다.'))
    body.addWidget(w.export_date_folder)
    folder_actions = QHBoxLayout()
    w.button(tr('폴더 선택'), w.choose_output, folder_actions)
    w.button(tr('선택한 폴더 열기'), w.open_output_folder, folder_actions)
    body.addLayout(folder_actions)
    body.addWidget(QLabel(tr('저장할 파일명')))
    body.addWidget(QLabel(tr('동일한 파일명에는 번호를 붙입니다.')))
    w.output_names = QListWidget()
    body.addWidget(w.output_names, 1)
    body.addWidget(w.export_settings_summary)
    export_actions = QHBoxLayout()
    w.button(tr('저장 설정'), w.show_export_settings, export_actions)
    w.execute_export_button = w.button(tr('파일 저장 시작'), w.execute_export, export_actions)
    w.execute_export_button.setProperty("primary", True)
    body.addLayout(export_actions)
    body = page(tr('YouTube · 선택 구간 다운로드'))
    w.youtube_info = QLabel()
    w.youtube_info.setTextFormat(Qt.TextFormat.PlainText)
    w.youtube_info.setWordWrap(True)
    body.addWidget(w.youtube_info)
    remote_form = QFormLayout()
    w.youtube_start, w.youtube_end = QLineEdit(), QLineEdit()
    remote_form.addRow(tr('시작'), w.youtube_start)
    remote_form.addRow(tr('끝'), w.youtube_end)
    body.addLayout(remote_form)
    body.addWidget(QLabel(tr('동시 다운로드 수')))
    w.download_workers = QSlider(Qt.Orientation.Horizontal)
    w.download_workers.setObjectName('download_workers')
    w.download_workers.setAccessibleName(tr('동시 다운로드 수'))
    w.download_workers.setRange(1, 16)
    w.download_workers.setTickInterval(1)
    w.download_workers.setTickPosition(QSlider.TickPosition.TicksBelow)
    w.download_workers.setStyleSheet('''
        QSlider::groove:horizontal { height: 6px; border-radius: 3px;
          background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
            stop:0 #23834b, stop:0.2333 #23834b, stop:0.2334 #bd3434, stop:1 #bd3434); }
        QSlider::handle:horizontal { width: 16px; margin: -5px 0;
          background: palette(button); border: 2px solid palette(text); border-radius: 8px; }
        QSlider:focus { border: 1px solid palette(highlight); }
    ''')
    w.download_workers_status = QLabel()
    w.download_workers_status.setWordWrap(True)
    def update_download_workers(value):
        recommended = value <= 4
        w.download_workers_status.setText(
            tr('{count}개 · 권장 범위 (1–4)', count=value) if recommended else
            tr('{count}개 · 주의: 요청 제한 가능성 증가 (5–16)', count=value))
        w.download_workers_status.setStyleSheet('color: ' + ('#23834b' if recommended else '#bd3434'))
        w.download_workers.setAccessibleDescription(w.download_workers_status.text())
        QSettings('ArcadeClip', 'ArcadeClip').setValue('download_workers', value)
    settings = QSettings('ArcadeClip', 'ArcadeClip')
    try:
        workers = max(1, min(16, int(settings.value('download_workers', 4))))
    except (TypeError, ValueError):
        workers = 4
    w.download_workers.setValue(workers)
    w.download_workers.valueChanged.connect(update_download_workers)
    update_download_workers(workers)
    body.addWidget(w.download_workers)
    body.addWidget(w.download_workers_status)
    note = QLabel(tr('권장 범위에서도 요청이 제한될 수 있습니다. 오류가 나면 수를 줄이고 잠시 후 다시 시도하세요.'))
    note.setWordWrap(True)
    body.addWidget(note)
    w.busy_controls.append(w.download_workers)
    w.download = w.button(tr('선택 구간 다운로드'), w.download_range, body)
    w.download_progress = QProgressBar()
    w.download_progress.setRange(0, 100)
    w.download_progress.setValue(0)
    body.addWidget(w.download_progress)
    w.download_mode = QLabel()
    w.download_mode.setWordWrap(True)
    body.addWidget(w.download_mode)
    w.download_eta = QLabel()
    w.download_eta.setWordWrap(True)
    body.addWidget(w.download_eta)
    w.download_detail = QLabel(tr('다운로드 대기'))
    body.addWidget(w.download_detail)
    w.download_log = QPlainTextEdit()
    w.download_log.setReadOnly(True)
    w.download_log.setMaximumBlockCount(500)
    body.addWidget(w.download_log, 1)
    splitter.addWidget(w.detail_stack)
    # Keep the existing stage indices; time controls belong beside the timeline.
    w.detail_stack.removeWidget(w.time_controls)
    w.detail_stack.insertWidget(1, QWidget())
    center_layout.addWidget(w.time_controls)
    splitter.setStretchFactor(1, 1)
    splitter.setSizes([275, 705, 280])
    layout.addWidget(splitter, 1)
    w.analysis_panel = QWidget()
    analysis_layout = QVBoxLayout(w.analysis_panel)
    analysis_layout.setContentsMargins(0, 0, 0, 0)
    steps = QHBoxLayout()
    w.analysis_steps = []
    for name in (tr('1 데이터'), tr('2 위치 보정'), tr('3 곡 판독'), tr('4 경계 확인'), tr('5 문자·정리')):
        label = QLabel(name)
        w.analysis_steps.append(label)
        steps.addWidget(label)
    analysis_layout.addLayout(steps)
    w.analysis_detail = QLabel()
    analysis_layout.addWidget(w.analysis_detail)
    w.analysis_metrics = QLabel()
    w.analysis_metrics.setWordWrap(True)
    analysis_layout.addWidget(w.analysis_metrics)
    w.analysis_progress = QProgressBar()
    w.analysis_progress.setRange(0, 100)
    analysis_layout.addWidget(w.analysis_progress)
    w.analysis_panel.hide()
    layout.addWidget(w.analysis_panel)
    bottom = QHBoxLayout()
    w.status = QLabel(tr('영상을 추가해 주세요.'))
    w.status.setTextFormat(Qt.TextFormat.PlainText)
    w.status.setWordWrap(True)
    bottom.addWidget(w.status, 1)
    w.progress = QProgressBar()
    w.progress.setMaximumWidth(180)
    w.progress.hide()
    bottom.addWidget(w.progress)
    w.cancel = w.button(tr('취소'), w.cancel_task, bottom, busy=False)
    w.cancel.hide()
    layout.addLayout(bottom)
    w.busy_controls.extend((w.files, w.url, w.profile))
    w.setCentralWidget(root)
    w.stage_group.button(0).setChecked(True)
    w.update_selection_summary()
    w.set_stage(0)
